"""Change Meal and MealElement into Dish

Revision ID: 332152892216
Revises: 36a43524dcdf
Create Date: 2022-10-16 18:28:04.250157

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '332152892216'
down_revision = '36a43524dcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('category', sa.String(), nullable=False),
                    sa.Column('elements', sa.String(), nullable=True),
                    sa.Column('prep_notes', sa.String(), nullable=True),
                    sa.Column('prep_time_m', sa.Integer(), nullable=False),
                    sa.Column('cooking_notes', sa.String(), nullable=True),
                    sa.Column('cooking_time_m', sa.Integer(), nullable=False),
                    sa.Column('cooking_time_comments', sa.String(), nullable=True),
                    sa.Column('periodicity_d', sa.Integer(), nullable=False),
                    sa.Column('tags', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.drop_constraint("meal2mealhistory", type_='foreignkey')
    op.drop_table('meals')
    op.drop_table('meal_elements')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'meals', ['meal'], ['id'])

    op.create_table('meal_elements',
                    sa.Column('id', sa.VARCHAR(), nullable=False),
                    sa.Column('name', sa.VARCHAR(), nullable=True),
                    sa.Column('category', sa.VARCHAR(), nullable=True),
                    sa.Column('prep_notes', sa.VARCHAR(), nullable=True),
                    sa.Column('prep_time_m', sa.INTEGER(), nullable=True),
                    sa.Column('cooking_notes', sa.VARCHAR(), nullable=True),
                    sa.Column('cooking_time_m', sa.INTEGER(), nullable=True),
                    sa.Column('cooking_time_comments', sa.VARCHAR(), nullable=True),
                    sa.Column('periodicity_d', sa.INTEGER(), nullable=True),
                    sa.Column('tags', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('meals',
                    sa.Column('id', sa.VARCHAR(), nullable=False),
                    sa.Column('name', sa.VARCHAR(), nullable=True),
                    sa.Column('prep_notes', sa.VARCHAR(), nullable=True),
                    sa.Column('prep_time_m', sa.INTEGER(), nullable=True),
                    sa.Column('cooking_notes', sa.VARCHAR(), nullable=True),
                    sa.Column('cooking_time_m', sa.INTEGER(), nullable=True),
                    sa.Column('meal_type', sa.VARCHAR(length=13), nullable=True),
                    sa.Column('periodicity_d', sa.INTEGER(), nullable=True),
                    sa.Column('elements', sa.VARCHAR(), nullable=True),
                    sa.Column('cooking_time_comments', sa.VARCHAR(), nullable=True),
                    sa.Column('tags', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('dishes')
    # ### end Alembic commands ###
