"""Move list of ingredients in to dishes

Revision ID: 4fbc55b66d49
Revises: a4336e5ec6bb
Create Date: 2022-11-04 21:08:06.809297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbc55b66d49'
down_revision = 'a4336e5ec6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dishes', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    op.create_table('recipes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('ingredients', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
