"""Modify the Suggestion data model

Revision ID: 7ba513f484ec
Revises: 6796a4188bc9
Create Date: 2022-08-17 09:50:19.946250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ba513f484ec'
down_revision = '6796a4188bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        sa_enum = sa.Enum('lunch', 'dinner', name='mealtime')
        # This will create the enum if it's not already present which is helpful
        # (workaround postgresql: https://github.com/sqlalchemy/alembic/issues/278)
        sa_enum.create(batch_op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column('time', sa_enum, nullable=True))
        batch_op.add_column(sa.Column('eligible_meals', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('suggestion', sa.String(), nullable=True))
        batch_op.drop_column('lunches')
        batch_op.drop_column('duration')
        batch_op.drop_column('dinners')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dinners', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('lunches', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('suggestion')
        batch_op.drop_column('eligible_meals')
        batch_op.drop_column('time')

    # ### end Alembic commands ###
