"""Rename Ingredient column

Revision ID: a4336e5ec6bb
Revises: 332152892216
Create Date: 2022-10-24 21:49:43.206852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4336e5ec6bb'
down_revision = '332152892216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient', sa.String(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('ingredient')

    # ### end Alembic commands ###
